#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

use_frameworks!

target 'PLVRtmpDemo' do
    pod 'MBProgressHUD', '~> 1.1.0'
    
    pod 'PLVLiveKit', '~> 1.2.3'        # polyv streamer.
    pod 'PolyvLiveAPI', '~> 0.7.1'      # Polyv live api.
    pod 'PolyvSocketAPI', '~> 0.6.1'    # Polyv socket.io api.
    #pod 'Starscream', '3.0.5'           # Xcode 10 以下解注释
end
